#Workflow
name: Deploy To S3 And Invalidate Cloudfront

on:
  push:
    branches:
      - main

#Workflow는 여러개의 Job으로 이루어질 수 있고
jobs:
  Deploy-Job:
    runs-on: ubuntu-latest
    #하나의 Job은 여러개의 Step으로 이루어져있다.
    steps:
      - name: Github repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: AWS Resource에 접근할 수 이?ㅆ게 AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northheast-2
          aws-access-key-id: ${{secrets.AWS_ACESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACESS_KEY}}

      - name: S3 기존 파일 전체 삭제
        run: |
          aws s3 rm --rescursive s3://facebook-webb
