#Workflow
name: Github Actions 실행시켜보기

on:
  push:
    branches: -main

#Workflow는 여러개의 Job으로 이루어짐
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"
